### PR TITLE
Add package discovery to composer

### PR DESCRIPTION
**Pull request by piperone**
For Laravel 5.5

### CODE REVIEW

**Comment by lukeramsden** [comment]
This should be merged, but I don't think the author is active anymore... Time to publish your own fork?

**Comment by Grimthorr** [comment]
Sorry, I haven't used Laravel in a while so development on this has been paused somewhat.

I can merge this, but are there any other changes necessary to make this package compatible with Laravel 5.5?

**Comment by lukeramsden** [comment]
Not that I know of, I'm planning on integrating this in to my project today so I can let you know of any problems I run in to.

PS: That was a very quick response.

**Comment by piperone** [comment]
I'm using this package in L5.5 without any issue. This PR is more of a convenience; with it, you no longer have to add the service-provider and facade to Laravel's app.php config-file.

**Comment by Grimthorr** [comment]
Ok sounds good to me, thanks. I've squashed, merged and released as version 1.1.1.

PS: I must have missed the notification for this PR originally, so sorry for the (very) late reply!

**Pull request merged**
